### ISSUE TITLE
Floating Menu?

### ISSUE THREAD

**Issue by opb** [CouscousPHP/Template-ReadTheDocs#2]
Are there any options for floating the menu so that it's viewable on long pages?

Thanks

**Comment by mnapoli** [comment]
Hi, currently I don't think so. The main problem with floating left menus is when the menu is taller than the screen height (and it can happen often with small screens). In those cases you can't even scroll the menu which is quite embarrassing :/

Feel free to work on this though if you want, I'd happily merge it.

**Comment by opb** [comment]
Hi

thanks for the offer. I ended up hacking around with the theme quite a bit, so probably (definitely!) not good enough for a merge. Thanks anyway!
